name: 'build docker images: Postgres 14 + PostGIS'

on:
  #push:
  #  branches:
  #    - 'main'
  #    - 'master'
  #  paths:
  #    - 'alpine.Dockerfile'
  #    - '.github/workflows/build_docker_images-postgres14postgis.yaml'
  workflow_dispatch:
  schedule:
    - cron: '30 5 24 * *'  # At 05:30 on day-of-month 24.

defaults:
  run:
    shell: bash

jobs:
  postgis-arm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Shell-Script
        id: script
        run: |
          BUILD_DATE="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          BUILD_DATE_NUMERIC="${BUILD_DATE//[^[:digit:]]/}"
          COMMIT_HASH=${GITHUB_SHA::7}
          GITHUB_REPO=${GITHUB_REPOSITORY,,}
          GITHUB_REPO_SHORT=${GITHUB_REPO#*/}
          GITHUB_REPO_SHORT=${GITHUB_REPO_SHORT#"docker-"}
          #DOCKER_REPO=${{ secrets.DOCKER_USERNAME }}/${GITHUB_REPO_SHORT}
          DOCKER_REPO=${{ secrets.DOCKER_USERNAME }}/rpi-postgresql-postgis
          #REDHAT_QUAY_REPO=${{ secrets.REDHAT_QUAY_USERNAME }}/${GITHUB_REPO_SHORT}
          
          # Set output parameters to action.
          echo "build_date=${BUILD_DATE}" >> "$GITHUB_OUTPUT"
          echo "build_date_numeric=${BUILD_DATE_NUMERIC}" >> "$GITHUB_OUTPUT"
          echo "commit_hash=${COMMIT_HASH}" >> "$GITHUB_OUTPUT"
          echo "github_repo=${GITHUB_REPO}" >> "$GITHUB_OUTPUT"
          echo "docker_repo=${DOCKER_REPO}" >> "$GITHUB_OUTPUT"
          echo "redhat_quay_repo=${REDHAT_QUAY_REPO}" >> "$GITHUB_OUTPUT"

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      #- name: Login to GitHub Container Registry
      #  uses: docker/login-action@v3
      #  with:
      #    registry: ghcr.io
      #    username: ${{ github.repository_owner }}
      #    password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub 
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      #- name: Login to RED HAT Quay.io Container Registry
      #  uses: docker/login-action@v3
      #  with:
      #    registry: quay.io
      #    username: ${{ secrets.REDHAT_QUAY_USERNAME }}
      #    password: ${{ secrets.REDHAT_QUAY_PASSWORD }}

      - name: Build
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./alpine.Dockerfile
          platforms: linux/arm/v7
          pull: true
          push: true
          build-args: |
             POSTGRES_VERSION=14
          #  BUILD_DATE=${{steps.script.outputs.build_date}}
          #  VCS_REF=${{steps.script.outputs.commit_hash}}
          tags: |
            docker.io/${{steps.script.outputs.docker_repo}}:14-3.5-alpine-arm
          #  ghcr.io/${{steps.script.outputs.github_repo}}:14-3.5-alpine-arm
          #  quay.io/${{steps.script.outputs.redhat_quay_repo}}:14-3.5-alpine-arm

  postgis-arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Shell-Script
        id: script
        run: |
          BUILD_DATE="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          BUILD_DATE_NUMERIC="${BUILD_DATE//[^[:digit:]]/}"
          COMMIT_HASH=${GITHUB_SHA::7}
          GITHUB_REPO=${GITHUB_REPOSITORY,,}
          GITHUB_REPO_SHORT=${GITHUB_REPO#*/}
          GITHUB_REPO_SHORT=${GITHUB_REPO_SHORT#"docker-"}
          #DOCKER_REPO=${{ secrets.DOCKER_USERNAME }}/${GITHUB_REPO_SHORT}
          DOCKER_REPO=${{ secrets.DOCKER_USERNAME }}/rpi-postgresql-postgis
          #REDHAT_QUAY_REPO=${{ secrets.REDHAT_QUAY_USERNAME }}/${GITHUB_REPO_SHORT}
          
          # Set output parameters to action.
          echo "build_date=${BUILD_DATE}" >> "$GITHUB_OUTPUT"
          echo "build_date_numeric=${BUILD_DATE_NUMERIC}" >> "$GITHUB_OUTPUT"
          echo "commit_hash=${COMMIT_HASH}" >> "$GITHUB_OUTPUT"
          echo "github_repo=${GITHUB_REPO}" >> "$GITHUB_OUTPUT"
          echo "docker_repo=${DOCKER_REPO}" >> "$GITHUB_OUTPUT"
          echo "redhat_quay_repo=${REDHAT_QUAY_REPO}" >> "$GITHUB_OUTPUT"

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      #- name: Login to GitHub Container Registry
      #  uses: docker/login-action@v3
      #  with:
      #    registry: ghcr.io
      #    username: ${{ github.repository_owner }}
      #    password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub 
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      #- name: Login to RED HAT Quay.io Container Registry
      #  uses: docker/login-action@v3
      #  with:
      #    registry: quay.io
      #    username: ${{ secrets.REDHAT_QUAY_USERNAME }}
      #    password: ${{ secrets.REDHAT_QUAY_PASSWORD }}

      - name: Build
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./alpine.Dockerfile
          platforms: linux/arm64/v8
          pull: true
          push: true
          build-args: |
             POSTGRES_VERSION=14
          #  BUILD_DATE=${{steps.script.outputs.build_date}}
          #  VCS_REF=${{steps.script.outputs.commit_hash}}
          tags: |
            docker.io/${{steps.script.outputs.docker_repo}}:14-3.5-alpine-arm64
          #  ghcr.io/${{steps.script.outputs.github_repo}}:14-3.5-alpine-arm64
          #  quay.io/${{steps.script.outputs.redhat_quay_repo}}:14-3.5-alpine-arm64

  postgis-amd64:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Shell-Script
        id: script
        run: |
          BUILD_DATE="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          BUILD_DATE_NUMERIC="${BUILD_DATE//[^[:digit:]]/}"
          COMMIT_HASH=${GITHUB_SHA::7}
          GITHUB_REPO=${GITHUB_REPOSITORY,,}
          GITHUB_REPO_SHORT=${GITHUB_REPO#*/}
          GITHUB_REPO_SHORT=${GITHUB_REPO_SHORT#"docker-"}
          #DOCKER_REPO=${{ secrets.DOCKER_USERNAME }}/${GITHUB_REPO_SHORT}
          DOCKER_REPO=${{ secrets.DOCKER_USERNAME }}/rpi-postgresql-postgis
          #REDHAT_QUAY_REPO=${{ secrets.REDHAT_QUAY_USERNAME }}/${GITHUB_REPO_SHORT}
          
          # Set output parameters to action.
          echo "build_date=${BUILD_DATE}" >> "$GITHUB_OUTPUT"
          echo "build_date_numeric=${BUILD_DATE_NUMERIC}" >> "$GITHUB_OUTPUT"
          echo "commit_hash=${COMMIT_HASH}" >> "$GITHUB_OUTPUT"
          echo "github_repo=${GITHUB_REPO}" >> "$GITHUB_OUTPUT"
          echo "docker_repo=${DOCKER_REPO}" >> "$GITHUB_OUTPUT"
          echo "redhat_quay_repo=${REDHAT_QUAY_REPO}" >> "$GITHUB_OUTPUT"

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      #- name: Login to GitHub Container Registry
      #  uses: docker/login-action@v3
      #  with:
      #    registry: ghcr.io
      #    username: ${{ github.repository_owner }}
      #    password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub 
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      #- name: Login to RED HAT Quay.io Container Registry
      #  uses: docker/login-action@v3
      #  with:
      #    registry: quay.io
      #    username: ${{ secrets.REDHAT_QUAY_USERNAME }}
      #    password: ${{ secrets.REDHAT_QUAY_PASSWORD }}

      - name: Build
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./alpine.Dockerfile
          platforms: linux/amd64
          pull: true
          push: true
          build-args: |
             POSTGRES_VERSION=14
          #  BUILD_DATE=${{steps.script.outputs.build_date}}
          #  VCS_REF=${{steps.script.outputs.commit_hash}}
          tags: |
            docker.io/${{steps.script.outputs.docker_repo}}:14-3.5-alpine-amd64
          #  ghcr.io/${{steps.script.outputs.github_repo}}:14-3.5-alpine-amd64
          #  quay.io/${{steps.script.outputs.redhat_quay_repo}}:14-3.5-alpine-amd64
